### ISSUE TITLE
Native Library bluecove_x64 not available

### ISSUE THREAD

**Issue by pmfg** [ricardofalcao/Bluetooth-Serial-Communication#1]
When trying to run the program gives the following error (x64 OS Linux Mint 20.1 / openjdk version "11.0.9.1" 2020-11-04)
![2021-01-24_19-54](https://user-images.githubusercontent.com/10880978/105641863-1f5cd580-5e7e-11eb-818b-442b87f9981d.png)

Possible fix:
https://stackoverflow.com/questions/16886146/error-in-bluetooth-device-discovery

**Comment by ricardofalcao** [comment]
The provided SO discussion recommends updating the 64 bit version of BlueCove, which was already done in the past.
Before further investigation, could you make sure you have all the dependencies installed in your system?
As specified in [this page](http://bluecove.org/bluecove-gpl/), you must have the `bluez` and the `libbluetooth-dev` packages installed:

`sudo apt-get install bluez libbluetooth-dev`

**Comment by pmfg** [comment]
With the installation of the remaining dependencies work. Thanks
sudo apt-get install bluez libbluetooth-dev
